server:
  port: 7000
  servlet:
    context-path: /ad-sopnsor
spring:
  application:
    name: eureka-client-ad-sponsor
   jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate.format_sql: true
      open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud?autoReconnect=true
    username: root
    password: 123456
    tomcat:
      max-active: 20
      min-idle: 4
      initial-size: 2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
